### ISSUE TITLE
NullPointerException when obtaining feeds

### ISSUE THREAD

**Issue by mvysny** [sola92/Instagram-Java#14]
Hi, on my account when I try to obtain the user's feed I receive this NPE instead:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject org.json.JSONObject.optJSONObject(java.lang.String)' on a null object reference
                                                                              at com.sola.instagram.util.PaginationIterator.fetch(PaginationIterator.java:48)
                                                                              at com.sola.instagram.util.PaginationIterator.<init>(PaginationIterator.java:20)
                                                                              at com.sola.instagram.InstagramSession$2.<init>(InstagramSession.java:147)
                                                                              at com.sola.instagram.InstagramSession.getFeed(InstagramSession.java:147)
```

Would you perhaps know what's causing this?

**Comment by mvysny** [comment]
Aha! When getting https://api.instagram.com/v1/users/self/feed, instagram replies with 

"Sorry, this page isn't available. The link you followed may be broken, or the page may have been removed. Go back to Instagram."

So, with a HTML file. Naturally, JSON parser can't parse that:

```
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
01-25 15:40:06.880 10514-13308/sk.baka.photoframe W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
01-25 15:40:06.880 10514-13308/sk.baka.photoframe W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
01-25 15:40:06.880 10514-13308/sk.baka.photoframe W/System.err:     at com.sola.instagram.io.RequestResponse.getJSON(RequestResponse.java:17)
01-25 15:40:06.880 10514-13308/sk.baka.photoframe W/System.err:     at com.sola.instagram.util.PaginationIterator.fetch(PaginationIterator.java:46)
01-25 15:40:06.880 10514-13308/sk.baka.photoframe W/System.err:     at com.sola.instagram.util.PaginationIterator.<init>(PaginationIterator.java:20)
01-25 15:40:06.880 10514-13308/sk.baka.photoframe W/System.err:     at com.sola.instagram.InstagramSession$2.<init>(InstagramSession.java:147)
01-25 15:40:06.880 10514-13308/sk.baka.photoframe W/System.err:     at com.sola.instagram.InstagramSession.getFeed(InstagramSession.java:147)
01-25 15:40:06.880 10514-13308/sk.baka.photoframe W/System.err:     at sk.baka.photoframe.fsimpl.instagram.InstagramFileSystem.list(InstagramFileSystem.java:58)
01-25 15:40:06.880 10514-13308/sk.baka.photoframe W/System.err:     at sk.baka.photoframe.fs.CacheFileSystem.list(CacheFileSystem.java:91)
01-25 15:40:06.880 10514-13308/sk.baka.photoframe W/System.err:     at sk.baka.photoframe.fsimpl.cache.ThumbnailCache$ThumbnailCacheFileSystem.list(ThumbnailCache.java:130)
01-25 15:40:06.881 10514-13308/sk.baka.photoframe W/System.err:     at sk.baka.photoframe.browser.GalleryFSFragment$DirContentsLoader.loadItemsInBackground(GalleryFSFragment.java:279)
01-25 15:40:06.881 10514-13308/sk.baka.photoframe W/System.err:     at sk.baka.aedict.util.LoaderEx$Loader.run(LoaderEx.java:179)
01-25 15:40:06.881 10514-13308/sk.baka.photoframe W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-25 15:40:06.881 10514-13308/sk.baka.photoframe W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-25 15:40:06.881 10514-13308/sk.baka.photoframe W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

Seems that Instagram removed that particular endpoint: can't find it in Instagram REST API. Also see this: http://stackoverflow.com/questions/33888658/instagram-users-self-feed-404-errorcode

**Comment by mvysny** [comment]
Okay, so Instagram deprecated self/feed and there is no replacement. I will perhaps use self/media/recent
